# Generated by Django 5.0.6 on 2024-06-10 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_educ_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('preferred_student_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('any', 'Any')], default='any', help_text='Preferred gender of the student.', max_length=10)),
                ('tuition_amount_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum tuition amount the sponsor is willing to provide.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('tuition_amount_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum tuition amount the sponsor is willing to provide.', max_digits=10, null=True, validators=[django.core.validators.MaxValueValidator(0)])),
                ('preferred_student_courses', models.CharField(choices=[('sciences', 'Sciences'), ('arts', 'Arts'), ('any', 'Any')], default='any', help_text='Preferred course of study for the student.', max_length=20)),
                ('weight_student_gender', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('weight_student_courses', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('weight_tuition', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
