# Generated by Django 5.0.6 on 2024-06-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_educ_site', '0002_sponsorpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorpreferences',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
