# Generated by Django 5.0.6 on 2024-06-13 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('u_educ_site', '0005_rename_phone_number_sponsorpreferences_phonenumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorpreferences',
            name='profileImage',
        ),
    ]
