# Generated by Django 5.0.6 on 2024-06-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_educ_site', '0007_alter_sponsorpreferences_tuition_amount_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorpreferences',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
