# Generated by Django 5.0.6 on 2024-07-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_educ_site', '0009_mappings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappings',
            name='studentPhoneNumber',
        ),
        migrations.AddField(
            model_name='mappings',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mappings',
            name='studentGender',
            field=models.TextField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='mappings',
            name='tuitionAmountPerSemester',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='mappings',
            name='yearOfStudy',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
