# Generated by Django 5.0.6 on 2024-06-25 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FamEducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_status', models.CharField(max_length=50)),
                ('father_surname', models.CharField(max_length=100)),
                ('father_given_name', models.CharField(max_length=100)),
                ('father_national_id', models.CharField(max_length=50)),
                ('father_national_id_picture_url', models.URLField()),
                ('mother_status', models.CharField(max_length=50)),
                ('mother_surname', models.CharField(max_length=100)),
                ('mother_given_name', models.CharField(max_length=100)),
                ('mother_national_id', models.CharField(max_length=50)),
                ('mother_national_id_picture_url', models.URLField()),
                ('guardian_surname', models.CharField(max_length=100)),
                ('guardian_given_name', models.CharField(max_length=100)),
                ('guardian_national_id', models.CharField(max_length=50)),
                ('guardian_national_id_picture_url', models.URLField()),
                ('student_status', models.CharField(max_length=50)),
                ('reg_no', models.CharField(max_length=50)),
                ('student_no', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('arts_or_sciences', models.CharField(max_length=50)),
                ('year_of_study', models.CharField(max_length=10)),
                ('current_cgpa', models.CharField(max_length=10)),
                ('tuition_amount_per_semester', models.CharField(max_length=20)),
                ('picture_of_portal_url', models.URLField()),
                ('school_name', models.CharField(max_length=100)),
                ('school_location', models.CharField(max_length=100)),
                ('year_of_sitting', models.CharField(max_length=10)),
                ('subject_one_name', models.CharField(max_length=50)),
                ('subject_one_grade', models.CharField(max_length=10)),
                ('subject_one_points', models.CharField(max_length=10)),
                ('subject_two_name', models.CharField(max_length=50)),
                ('subject_two_grade', models.CharField(max_length=10)),
                ('subject_two_points', models.CharField(max_length=10)),
                ('subject_three_name', models.CharField(max_length=50)),
                ('subject_three_grade', models.CharField(max_length=10)),
                ('subject_three_points', models.CharField(max_length=10)),
                ('subsidiary_one_name', models.CharField(max_length=50)),
                ('subsidiary_one_grade', models.CharField(max_length=10)),
                ('subsidiary_one_points', models.CharField(max_length=10)),
                ('subsidiary_two_name', models.CharField(max_length=50)),
                ('subsidiary_two_grade', models.CharField(max_length=10)),
                ('subsidiary_two_points', models.CharField(max_length=10)),
                ('total_points', models.CharField(max_length=10)),
                ('picture_of_pass_slip_url', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='DetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('other_names', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.usermodel')),
            ],
        ),
    ]
