# Generated by Django 5.0.6 on 2024-06-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_rename_other_names_detailsmodel_othernames_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsmodel',
            name='userId',
            field=models.TextField(max_length=100),
        ),
    ]
