# Generated by Django 5.0.6 on 2024-06-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_alter_detailsmodel_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fameducationmodel',
            name='userId',
            field=models.TextField(max_length=100),
        ),
    ]
