# Generated by Django 5.0.6 on 2024-06-25 09:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_alter_fameducationmodel_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='fameducationmodel',
            name='subjectOneName',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
