# Generated by Django 5.0.6 on 2024-07-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_fameducationmodel_subjectonename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fameducationmodel',
            name='userId',
            field=models.TextField(max_length=200),
        ),
    ]
